language: java
jdk:
- oraclejdk8
install: true
script:
- curl -O https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
- chmod a+x lein
- lein test
- chmod a+x funimagej_deploy.sh
- bash funimagej_deploy.sh
env:
  global:
  - secure: J9+BIg669YvVvr4vw9XC1Oo6UVHHKUl1Z0UridQGnpD4w0tPFc+uL8KscBSw6DEf0EI1a78H/6z4QJirgKqI4S83abPQFhBRpEeoMsvoVeby1si6iuIqk738xrMMsg/5XTHuEtVhn+CFx7XatcJ0fJTzzU8sbDrRT7VWS+plC+n8xyLTPvyBl418lqCXXBKag+BvoAJsZn0NTA8VzUDzLM/+ozCFMhqINjIo6VZxno+iiCqlqBVP+lOAYVwDfrmOFkSde3nx/VRgoHAobVES+Qf7zkEiXeAiAMawU8kv1PfssevqOb4irYoHoCDJuFPymXf6yRV8tez86Hs/KuxnBhARj8J2vYEL5aQ4PbDRMV89zemjDKPtUJTusZYM61d3ysZxY4dXVlG2fxW/zMhKdY2BCFUKwz4s6n2FVvAZr8KYzyLOxEZPxxu7RnIwup443OwhtRyVFeDy1KgI6qXhZubvNxNFv9/pX5yP0+gj/432+wUyrUtawxwbM+OSWEaA26I3T34Sv7OFjXV6sIPgkTuuaQVclrLvFRVWghIoGKMYx4BY3QLjwvc4XEM+Ut1JfoeYf2qW+zzk9V6QJAhjamd9pQ4M2f/PNdoQBnrZtgMNRMI2zC1j1f+N7hN5YiYQED1Tzz+5sxgNNp/KL/cvX3PPXmrI5YBGJyv+xeg1bh4=
  - secure: FPYudLTYMarS4mLfirlZfXp031eNzZKBt5IZJobsXgyzd0SQIUqVBVTn98w6LPiUHhml1JYVfyGXYP/50Vcuu+ODYntvdNhwd8I7rjV8G9gMWOqP/ihuVQ0zZQMSXhVFguhP+IzV6TYmweE4sUFm7swyHcEgdyUwbIyrkg9md6vyc4R/R7BgD+wCyNB/aFlBwCJZiYP7iE2v+N177KCB8td1t6JdV4O6GO/A3iemQOt5ik/qV42rzdYZr8WKgztvaLKMXprwFodKIoCrkq6sV8dZXY5GQ1Vbo8JBRdipqyUqNJzocqp478TiZKaMc1THl+rT/TKo2KWwGouoml6paFB8F9vYdOGLuj5tqPCPao0wsl+eeUX0eN+AYJ16EnQ8VjXPGGMMRr1Sgzf/fi1no6B4NS7+77jp6HCXTGxsCGnRsZExeMX4Lg7/zfdCmIsETsGnD9Sebtwk4xPcRI7GkfNi50bdV050/b9yTTSz18B19HoiwGbGBNBPDjaspEP8Pr3OtIIE5uP+h5b4Eyg8FyB5cP8x/dqoESmbaYz9cj4W+IuHSFUd8EsN1Uaqw5aUEMQPAe+1K40mwaybw1bSnhj+GAtyiomn7QhA6DHHvO1olYe9mhLszgWqi/TfBFtMWedFUX9t71e7S3G2ZwL9gFvOjWFNyzbUzlQI2RZ/KmU=
